=== nabinkrpal/frontend/student.dtd
<!ELEMENT studentProfile (student+)>
<!ELEMENT student (rollNo, name, age, semester, email, phone, department, applied)>
<!ELEMENT rollNo (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT applied (#PCDATA)>
<!-- 4th -->

=== nabinkrpal/frontend/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentProfile SYSTEM "student.dtd">

<studentProfile>
    <student>
        <rollNo>102345</rollNo>
        <name>Jhon Gab</name>
        <age>22</age>
        <semester>4</semester>
        <email>jhonny@example.com</email>
        <phone>9876543210</phone>
        <department>CSE</department>
        <applied>true</applied>
    </student>
</studentProfile>
